### ISSUE TITLE
com.jcabi.ssl.maven.plugin.KeytoolTest fails

### ISSUE THREAD

**Issue by wentwog** [jcabi/jcabi-ssl-maven-plugin#10] opened 2014-12-28 12:09 UTC
see the [log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/45272307/log.txt).
```
Expected: a string containing "localhost"  but: was "".
```
And this is despite 
```
[info] Keystore created in '/tmp/junit8976659806579518028/keystore.jks' (42 bytes)
[info] >> 
[info] >> Keystore type: JKS
[info] >> Keystore provider: SUN
[info] >> 
[info] >> Your keystore contains 1 entry
[info] >> 
[info] >> Alias name: localhost                           <--------------
[info] >> Creation date: Dec 28, 2014
[info] >> Entry type: PrivateKeyEntry
```

The test passes locally for me.

**Comment by dmarkov** [comment] 2015-01-14 13:24
@flexelem you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; -60 added to your rating, at the moment it is: -245

**Comment by dmarkov** [comment] 2015-01-20 07:14
@jenya this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here

Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by dmarkov** [comment] 2015-01-21 13:30
@dpisarenko it's yours, please go ahead

**Comment by dpisarenko** [comment] 2015-01-21 19:50
@dmarkov I can't reproduce this error on my machine, please give the task to someone else.

**Comment by dmarkov** [comment] 2015-01-22 11:39
> @dmarkov I can't reproduce this error on my machine, please give the task to someone else.

@dpisarenko right, I'll try to find someone else for this task

**Comment by dmarkov** [comment] 2015-06-30 07:13
@suseika it's yours, budget is 30 mins, please go ahead

**Comment by Suseika** [comment] 2015-06-30 18:28
@dmarkov I'm done here, closed in #35

**Comment by Suseika** [comment] 2015-06-30 18:30
@wentwog I fixed this issue, please see #35

**Comment by dmarkov** [comment] 2015-07-01 07:32
@rultor @wentwog please take a look, rultor closed it automatically

**Closed** 2015-07-01 10:32 UTC
Labels: 30 mins, @suseika, bug, DEV

**Comment by dmarkov** [comment] 2015-07-02 12:37
@suseika Thank you, I have added **45 mins** to your account in payment/transaction "`AP-9N90026730426194L`", time consumed: 28 hours and 5 mins; m=1685, that's why a bonus here for fast delivery; added +45 to your rating, now it is equal to [+278](http://www.netbout.com/b/35381?open=rating)
