### ISSUE TITLE
KeygenMojo.execute():121. We should call  truststore.populate() outside of the surrounding if

### ISSUE THREAD

**Issue by wentwog** [jcabi/jcabi-ssl-maven-plugin#17] opened 2015-01-08 11:37 UTC
Cos we need to populate mvn props always, not only when keystore is inactive.

**Comment by dmarkov** [comment] 2015-01-13 08:21
I'll find a developer for the task soon...

**Comment by dmarkov** [comment] 2015-01-14 13:24
@romankisilenko please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have. **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by dmarkov** [comment] 2015-01-14 13:27
@wentwog thanks for the report, I topped your acc for 15 mins, payment ID `50259212`

**Comment by dmarkov** [comment] 2015-01-28 11:39
@romankisilenko just a reminder that you're working with this task for 15 days already. -30 added to your rating, at the moment it is: +360

**Comment by RomanKisilenko** [comment] 2015-02-01 12:10
@wentwog Please close this issue, the PR is already reviewed and closed some time ago.

**Comment by wentwog** [comment] 2015-02-01 12:31
@RomanKisilenko could you please point me to the PR by referencing its number here?

**Comment by RomanKisilenko** [comment] 2015-02-01 12:41
@wentwog https://github.com/jcabi/jcabi-ssl-maven-plugin/pull/22

**Closed** 2015-02-01 13:41 UTC
Labels: 30 mins, @romankisilenko, bug, DEV

**Comment by wentwog** [comment] 2015-02-01 13:44
@dmarkov or @yegor256 please, make a release.

**Comment by yegor256** [comment] 2015-02-01 15:13
@rultor release, tag is `0.11`

**Comment by dmarkov** [comment] 2015-02-06 07:23
@romankisilenko thanks, I just added **30 mins** to your account, payment `51288039`... added +30 to your rating, now it is equal to +390
