### ISSUE TITLE
we should set truststore's path and pwd to maven project properties. As we do with keystore.

### ISSUE THREAD

**Issue by wentwog** [jcabi/jcabi-ssl-maven-plugin#8] opened 2014-12-28 11:09 UTC
If we don't then the truststore created upon the plugin execution will not be used if we initialize our truststore as described [here] (http://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html#CustomizingStores).

And this method of truststore initialization is the one we use in tests, for example.

This issue need to be fixed in order for [other](https://github.com/yegor256/s3auth/issues/191) issue be fixed

**Comment by dmarkov** [comment] 2015-01-01 13:16
@wentwog thank you for reporting this, I added 15 mins to your acc, transaction `49704922`

**Comment by wentwog** [comment] 2015-01-07 17:20
@dmarkov PL is merged.
Can I have additional 30m in this task since additional time have been required to implemented unit test we had discussed with @yegor256.

**Comment by yegor256** [comment] 2015-01-07 17:30
@wentwog if you think that the problem is solved, close the issue. You're the reporter, so you have to close it. Regarding the time, we don't do it like this. The budget is fixed and we don't extend it. Since you're just starting, we'll make an exception. In the future, keep in mind that all tasks are fixed-cost and never increase their budgets.

**Comment by yegor256** [comment] 2015-01-07 17:30
@dmarkov please add extra 30 mins to @wentwog

**Closed** 2015-01-07 17:32 UTC
Labels: 30 mins, bug, DEV, enhancement

**Comment by yegor256** [comment] 2015-01-07 21:13
@rultor release, tag is `0.10`

**Comment by yegor256** [comment] 2015-01-07 21:39
@rultor release, tag is `0.10`

**Comment by dmarkov** [comment] 2015-01-08 11:22
> @dmarkov please add extra 30 mins to @wentwog 

@yegor256 I've sent 30 mins extra to @wentwog in transaction ID "49978477"

**Comment by dmarkov** [comment] 2015-01-14 13:24
@wentwog Much obliged! I've added **30 mins** to your account in payment "50259067". +30 added to your rating, current score is: [+65](http://www.netbout.com/b/35104?open=rating)
