### ISSUE TITLE
s3auth build takes a lot of time (seems to hang)

### ISSUE THREAD

**Issue by dpisarenko** [jcabi/jcabi-ssl-maven-plugin#3] opened 2014-12-26 13:19 UTC
When I try to run `mvn clean install -Pqulice` in s3auth, I get lots of warnings like `takes mor
e than 1min, 14min already` and nothing seems to happen.

Here's the output:

```
DP118M@DP118M-PC /D/dev/teamed.io/s3auth (s3auth-202)
$ mvn clean install -Pqulice
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] s3auth
[INFO] s3auth-hosts
[INFO] s3auth-relay
[INFO] s3auth-rest
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building s3auth 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ s3auth ---
[INFO] Deleting d:\dev\teamed.io\s3auth\target
[INFO]
[INFO] --- jcabi-ssl-maven-plugin:0.7.22:keygen (default) @ s3auth ---
[ERROR] JSR-303 validator failed to initialize: Unable to create a Configuration
, because no Bean Validation provider could be found. Add a provider like Hibern
ate Validator (RI) to your classpath. (see http://www.jcabi.com/jcabi-aspects/js
r-303.html)
[INFO] jcabi-aspects 0.7.22/fd7496f started new daemon thread jcabi-loggable for
 watching of @Loggable annotated methods
[WARNING] #genkey(): takes more than 1min, 2min already, thread=main/RUNNABLE
[WARNING] #activate(d:\\dev\\teamed.io\\s3auth\\target\\keystore.jks): takes mor
e than 1min, 2min already, thread=main/RUNNABLE
[WARNING] #genkey(): takes more than 1min, 3min already, thread=main/RUNNABLE
[WARNING] #activate(d:\\dev\\teamed.io\\s3auth\\target\\keystore.jks): takes mor
e than 1min, 3min already, thread=main/RUNNABLE
[WARNING] #genkey(): takes more than 1min, 4min already, thread=main/RUNNABLE
[WARNING] #activate(d:\\dev\\teamed.io\\s3auth\\target\\keystore.jks): takes mor
e than 1min, 4min already, thread=main/RUNNABLE
[WARNING] #genkey(): takes more than 1min, 5min already, thread=main/RUNNABLE
[WARNING] #activate(d:\\dev\\teamed.io\\s3auth\\target\\keystore.jks): takes mor
e than 1min, 5min already, thread=main/RUNNABLE
[WARNING] #genkey(): takes more than 1min, 6min already, thread=main/RUNNABLE
[WARNING] #activate(d:\\dev\\teamed.io\\s3auth\\target\\keystore.jks): takes mor
e than 1min, 6min already, thread=main/RUNNABLE
[WARNING] #genkey(): takes more than 1min, 7min already, thread=main/RUNNABLE
[WARNING] #activate(d:\\dev\\teamed.io\\s3auth\\target\\keystore.jks): takes mor
e than 1min, 7min already, thread=main/RUNNABLE
[WARNING] #genkey(): takes more than 1min, 8min already, thread=main/RUNNABLE
[WARNING] #activate(d:\\dev\\teamed.io\\s3auth\\target\\keystore.jks): takes mor
e than 1min, 8min already, thread=main/RUNNABLE
[WARNING] #genkey(): takes more than 1min, 9min already, thread=main/RUNNABLE
[WARNING] #activate(d:\\dev\\teamed.io\\s3auth\\target\\keystore.jks): takes mor
e than 1min, 9min already, thread=main/RUNNABLE
[WARNING] #genkey(): takes more than 1min, 10min already, thread=main/RUNNABLE
[WARNING] #activate(d:\\dev\\teamed.io\\s3auth\\target\\keystore.jks): takes mor
e than 1min, 10min already, thread=main/RUNNABLE
[WARNING] #genkey(): takes more than 1min, 11min already, thread=main/RUNNABLE
[WARNING] #activate(d:\\dev\\teamed.io\\s3auth\\target\\keystore.jks): takes mor
e than 1min, 11min already, thread=main/RUNNABLE
[WARNING] #genkey(): takes more than 1min, 12min already, thread=main/RUNNABLE
[WARNING] #activate(d:\\dev\\teamed.io\\s3auth\\target\\keystore.jks): takes mor
e than 1min, 12min already, thread=main/RUNNABLE
[WARNING] #genkey(): takes more than 1min, 13min already, thread=main/RUNNABLE
[WARNING] #activate(d:\\dev\\teamed.io\\s3auth\\target\\keystore.jks): takes mor
e than 1min, 13min already, thread=main/RUNNABLE
[WARNING] #genkey(): takes more than 1min, 14min already, thread=main/RUNNABLE
[WARNING] #activate(d:\\dev\\teamed.io\\s3auth\\target\\keystore.jks): takes mor
e than 1min, 14min already, thread=main/RUNNABLE
```

I'm using Maven 3.2.2:

```
DP118M@DP118M-PC /D/dev/teamed.io/rultor (rultor-681)
$ mvn --version
Apache Maven 3.2.2 (45f7c06d68e745d05611f7fd14efb6594181933e; 2014-06-17T17:51:4
2+04:00)
Maven home: c:\Program Files\apache-maven-3.2.2
Java version: 1.7.0_45, vendor: Oracle Corporation
Java home: c:\Program Files\Java\jdk1.7.0_45\jre
Default locale: de_AT, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"
```

As stated in https://github.com/yegor256/s3auth/issues/234 , this is a bug in jcabi-ssl-maven-plugin.

How can I fix this error (make `mvn clean install -Pqulice` actually build s3auth in a reasonable time) ?

**Comment by AlexDag** [comment] 2015-01-14 23:09
@dmarkov , I'm starting this job.thanks

**Comment by dmarkov** [comment] 2015-01-16 12:46
@alexdag it takes too long. Usually, we expect any task to be finished in less than a week. I'll assign someone else. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. -60 added to your rating, current score is: [-180](http://www.netbout.com/b/35099?open=rating)

**Comment by AlexDag** [comment] 2015-01-16 14:09
@dmarkov two days ago I created issue about this task - https://github.com/jcabi/jcabi-ssl-maven-plugin/issues/20

**Comment by dmarkov** [comment] 2015-01-20 11:02
@oruam85 the task is yours, go ahead

**Comment by oruam85** [comment] 2015-01-22 01:22
@dmarkov @AlexDag i can not reproduce this bug because i dont have Win OS. In Linux works fine.

@dmarkov Please find somebody else for this bug.

**Comment by dmarkov** [comment] 2015-01-22 11:39
> @dmarkov @AlexDag i can not reproduce this bug because i dont have Win OS. In Linux works fine.
> 
> @dmarkov Please find somebody else for this bug.

@oruam85 all right, we'll find someone else for this task

**Comment by AlexDag** [comment] 2015-01-24 00:36
@dmarkov @oruam85  - are  there  any reason to try to test this issue above Win OS? Please, look at my comment, s3auth project try to use keytool from fixed Linux path, as "%/bin/keytool".This path is hardcoded.

**Comment by dmarkov** [comment] 2015-02-23 08:40
@adko-pl the task is yours, go ahead

**Comment by adko-pl** [comment] 2015-03-07 19:03
@dmarkov please find another developer

**Comment by yegor256** [comment] 2015-05-18 05:23
@dmarkov assign someone else here pls

**Comment by dmarkov** [comment] 2015-05-18 07:40
> @dmarkov assign someone else here pls

@yegor256 -30 points to your rating :(

**Comment by dmarkov** [comment] 2015-05-18 07:40
> @dmarkov assign someone else here pls

@yegor256 someone else will help in this task, no problem at all

**Comment by dmarkov** [comment] 2015-06-09 08:41
@suseika could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here

Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by Suseika** [comment] 2015-06-12 22:14
@dpisarenko I am unable to reproduce the issue. Here is my environment:

```
Apache Maven 3.2.2 (45f7c06d68e745d05611f7fd14efb6594181933e; 2014-06-17T18:51:42+05:00)
Maven home: C:\tools\apache-maven-3.2.2
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0_79\jre
Default locale: ru_RU, platform encoding: windows-1251
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
```

Are you still able to reproduce it? If not, I think this issue should be closed. Otherwise, if your `keytool` hangs, that's probably a misconfiguration of your own environment.

**Comment by Suseika** [comment] 2015-06-13 00:33
@dmarkov Please assign someone else for this task.

**Comment by dmarkov** [comment] 2015-06-15 07:54
> @dmarkov Please assign someone else for this task.

@suseika -30 points to your rating :(

**Comment by dmarkov** [comment] 2015-06-15 07:54
> @dmarkov Please assign someone else for this task.

@suseika I will try to find someone else

**Comment by dmarkov** [comment] 2015-09-30 07:52
@prondzyn it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket. Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by prondzyn** [comment] 2015-10-02 11:49
@dpisarenko both [yegor256/s3auth](https://github.com/yegor256/s3auth/) and [jcabi/jcabi-ssl-maven-plugin](https://github.com/jcabi/jcabi-ssl-maven-plugin) builds without problems on my machine. Do you still have the problem? My environment is below.

```
$ mvn -version
Apache Maven 3.2.2 (45f7c06d68e745d05611f7fd14efb6594181933e; 2014-06-17T15:51:42+02:00)
Maven home: C:\local\tools\apache-maven-3.2.2
Java version: 1.7.0_60, vendor: Oracle Corporation
Java home: C:\opt\java\jdk1.7.0\jre
Default locale: en_US, platform encoding: Cp1250
OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"
```

**Comment by dmarkov** [comment] 2015-10-15 10:58
@prondzyn the task is your hands for the last 15 days.. keep in mind that if it's not closed in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck

-30 added to your rating, current score is: [+45](http://www.netbout.com/b/35715?open=rating)

**Comment by prondzyn** [comment] 2015-10-15 11:20
@dmarkov please assign someone else as @dpisarenko does not response

**Comment by dmarkov** [comment] 2015-10-16 10:38
> @dmarkov please assign someone else as @dpisarenko does not response

@prondzyn 30 points deducted from your rating

**Comment by dmarkov** [comment] 2015-10-16 10:39
> @dmarkov please assign someone else as @dpisarenko does not response

@prondzyn I will assign somebody else to this issue

**Comment by dmarkov** [comment] 2016-08-08 07:26
@amihaiemil the task is yours please proceed

**Comment by amihaiemil** [comment] 2016-08-08 16:41
@dpisarenko Same as the guys above, I cannot reproduce it. 
My sepcs are: 

```
Windows 7, x86
Apache Maven 3.3.9
Jdk 1.7.0_79
```

It's been 1.5 years since you reported this, maybe it was fixed in the meantime. Please check and if it's ok, close this issue. 

Thanks, 
Mihai

**Comment by amihaiemil** [comment] 2016-08-10 06:33
@yegor256 Since I saw the author doesn't answer here, I wrote him an email explaining that neither me and other devs can reproduce the error. I asked him to have a look and close the issue if he cannot reproduce it. 

As I expected, he told me he doesn't work for Teamed and doesn't have the software to reproduce the bug anymore and that he cannot help me.

I asked him to close this issue but he didn't reply back and I see he hasn't closed it until now. 
Can you close it please? (I don't expect payment since I didn't do much here, but at least I would like to not have my rating dropped...)

**Comment by amihaiemil** [comment] 2016-08-12 13:40
@dpisarenko can you close this pls?

**Comment by amihaiemil** [comment] 2016-08-14 11:03
@dpisarenko ping

**Comment by amihaiemil** [comment] 2016-08-18 07:25
@dpisarenko ping

**Comment by amihaiemil** [comment] 2016-08-18 07:25
@yegor256 ping

**Comment by amihaiemil** [comment] 2016-08-18 12:45
@dpisarenko ping

**Comment by amihaiemil** [comment] 2016-08-20 16:14
@yegor256 ping

**Comment by amihaiemil** [comment] 2016-08-21 15:19
@dmarkov assign someone else

**Comment by dmarkov** [comment] 2016-08-22 08:22
> @dmarkov assign someone else

@amihaiemil 30 points was deducted from your rating

**Comment by dmarkov** [comment] 2016-08-22 08:22
> @dmarkov assign someone else

@amihaiemil OK, I will try to assign someone else

**Comment by yegor256** [comment] 2017-05-11 08:01
@dpisarenko I don't think it's reproducible any more

**Closed by yegor256** 2017-05-11 08:02 UTC
Labels: 30 mins, bug, DEV, invalid
